INSERT INTO public.databases (value, release_year) VALUES ('AMAZON_REDSHIFT', '2013');
INSERT INTO public.databases (value, release_year) VALUES ('APACHE_HBASE', '2008');
INSERT INTO public.databases (value, release_year) VALUES ('APACHE_HIVE', '2010');
INSERT INTO public.databases (value, release_year) VALUES ('CASSANDRA', '2008');
INSERT INTO public.databases (value, release_year) VALUES ('COUCH_BASE', '2010');
INSERT INTO public.databases (value, release_year) VALUES ('DYNAMO_DB', '2012');
INSERT INTO public.databases (value, release_year) VALUES ('ELASTIC_SEARCH', '2010');
INSERT INTO public.databases (value, release_year) VALUES ('FIREBASE', '2012');
INSERT INTO public.databases (value, release_year) VALUES ('GOOGLE_BIG_QUERY', '2010');
INSERT INTO public.databases (value, release_year) VALUES ('IBM_DB2', '1983');
INSERT INTO public.databases (value, release_year) VALUES ('MARIA_DB', '2009');
INSERT INTO public.databases (value, release_year) VALUES ('MEMCACHED', '2003');
INSERT INTO public.databases (value, release_year) VALUES ('MICROSOFT_AZURE_SQL_DB', '2010');
INSERT INTO public.databases (value, release_year) VALUES ('MICROSOFT_SQL_SERVER', '1989');
INSERT INTO public.databases (value, release_year) VALUES ('MONGO_DB', '2009');
INSERT INTO public.databases (value, release_year) VALUES ('MYSQL', '1995');
INSERT INTO public.databases (value, release_year) VALUES ('NEO4J', '2007');
INSERT INTO public.databases (value, release_year) VALUES ('ORACLE', '1979');
INSERT INTO public.databases (value, release_year) VALUES ('OTHER', '-');
INSERT INTO public.databases (value, release_year) VALUES ('POSTGRESQL', '1996');
INSERT INTO public.databases (value, release_year) VALUES ('REDIS', '2009');
INSERT INTO public.databases (value, release_year) VALUES ('SQL_LITE', '2000');
INSERT INTO public.databases (value, release_year) VALUES ('T_SQL', '1989');
INSERT INTO public.databases_types (value) VALUES ('CACHE');
INSERT INTO public.databases_types (value) VALUES ('DATA_STORE');
INSERT INTO public.databases_types (value) VALUES ('DATA_WAREHOUSE');
INSERT INTO public.databases_types (value) VALUES ('DOCUMENT_BASED');
INSERT INTO public.databases_types (value) VALUES ('GRAPH_DB');
INSERT INTO public.databases_types (value) VALUES ('NOSQL');
INSERT INTO public.databases_types (value) VALUES ('RELATIONAL');
INSERT INTO public.profiles_types (value) VALUES ('CLIENT_ADMIN');
INSERT INTO public.profiles_types (value) VALUES ('CLIENT_HIRER');
INSERT INTO public.profiles_types (value) VALUES ('SOFTWARE_DEVELOPER');
INSERT INTO public.profiles_types (value) VALUES ('TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('BUSINESS_ANALYSIS', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('CLOUD', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('DATABASE', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('DATA_SCIENCE', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('INFRASTRUCTURE', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('NETWORKING', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('OTHER', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('PRODUCT_MANAGEMENT', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('PROJECT_MANAGEMENT', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('SECURITY', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('SUPPORT', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('TEAM_MANAGEMENT', 'TECH_INDUSTRY');
INSERT INTO public.focus_areas (value, profile_type) VALUES ('TESTING', 'TECH_INDUSTRY');
INSERT INTO public.frameworks_categories (value) VALUES ('APPLICATION_FRAMEWORK');
INSERT INTO public.frameworks_categories (value) VALUES ('CMS');
INSERT INTO public.frameworks_categories (value) VALUES ('DATA_ANALYSIS');
INSERT INTO public.frameworks_categories (value) VALUES ('DEV_OPS');
INSERT INTO public.frameworks_categories (value) VALUES ('GAME_ENGINE');
INSERT INTO public.frameworks_categories (value) VALUES ('INFRASTRUCTURE');
INSERT INTO public.frameworks_categories (value) VALUES ('MACHINE_LEARNING');
INSERT INTO public.frameworks_categories (value) VALUES ('MOBILE_APP');
INSERT INTO public.frameworks_categories (value) VALUES ('NAVITE_APP');
INSERT INTO public.frameworks_categories (value) VALUES ('STREAM');
INSERT INTO public.frameworks_categories (value) VALUES ('TESTING_QA');
INSERT INTO public.frameworks_categories (value) VALUES ('WEB_FRAMEWORK');
INSERT INTO public.frameworks_categories (value) VALUES ('WEB_FRONTEND');
INSERT INTO public.frameworks_categories (value) VALUES ('WEB_SERVER');
INSERT INTO public.frameworks_types (value) VALUES ('FRAMEWORK');
INSERT INTO public.frameworks_types (value) VALUES ('INFRASTRUCTURE');
INSERT INTO public.frameworks_types (value) VALUES ('LIBRARY');
INSERT INTO public.frameworks_types (value) VALUES ('TOOL');
INSERT INTO public.programming_languages (value, release_year) VALUES ('ABAP', '1983');
INSERT INTO public.programming_languages (value, release_year) VALUES ('ASSEMBLY', '1947');
INSERT INTO public.programming_languages (value, release_year) VALUES ('BASH', '1989');
INSERT INTO public.programming_languages (value, release_year) VALUES ('CLOJURE', '2007');
INSERT INTO public.programming_languages (value, release_year) VALUES ('COFFEESCRIPT', '2009');
INSERT INTO public.programming_languages (value, release_year) VALUES ('C_PLUS_PLUS', '1983');
INSERT INTO public.programming_languages (value, release_year) VALUES ('C_SHARP', '2000');
INSERT INTO public.programming_languages (value, release_year) VALUES ('CSS', '1989');
INSERT INTO public.programming_languages (value, release_year) VALUES ('DART', '2011');
INSERT INTO public.programming_languages (value, release_year) VALUES ('DELPHI', '1995');
INSERT INTO public.programming_languages (value, release_year) VALUES ('D_ONLY', '2001');
INSERT INTO public.programming_languages (value, release_year) VALUES ('ELIXIR', '2012');
INSERT INTO public.programming_languages (value, release_year) VALUES ('ELM', '2012');
INSERT INTO public.programming_languages (value, release_year) VALUES ('ERLANG', '1986');
INSERT INTO public.programming_languages (value, release_year) VALUES ('FORTRAN', '1954');
INSERT INTO public.programming_languages (value, release_year) VALUES ('F_SHARP', '2005');
INSERT INTO public.programming_languages (value, release_year) VALUES ('GO', '2009');
INSERT INTO public.programming_languages (value, release_year) VALUES ('GROOVY', '2004');
INSERT INTO public.programming_languages (value, release_year) VALUES ('HASKELL', '1990');
INSERT INTO public.programming_languages (value, release_year) VALUES ('HTML', '1989');
INSERT INTO public.programming_languages (value, release_year) VALUES ('JAVA', '1995');
INSERT INTO public.programming_languages (value, release_year) VALUES ('JAVASCRIPT', '1995');
INSERT INTO public.programming_languages (value, release_year) VALUES ('JULIA', '2012');
INSERT INTO public.programming_languages (value, release_year) VALUES ('KOTLIN', '2011');
INSERT INTO public.programming_languages (value, release_year) VALUES ('LISP', '1959');
INSERT INTO public.programming_languages (value, release_year) VALUES ('LUA', '1993');
INSERT INTO public.programming_languages (value, release_year) VALUES ('MATLAB', '1978');
INSERT INTO public.programming_languages (value, release_year) VALUES ('OBJECTIVE_C', '1983');
INSERT INTO public.programming_languages (value, release_year) VALUES ('OCAML', '1996');
INSERT INTO public.programming_languages (value, release_year) VALUES ('PERL', '1987');
INSERT INTO public.programming_languages (value, release_year) VALUES ('PHP', '1995');
INSERT INTO public.programming_languages (value, release_year) VALUES ('POWERSHELL', '2006');
INSERT INTO public.programming_languages (value, release_year) VALUES ('PYTHON', '1989');
INSERT INTO public.programming_languages (value, release_year) VALUES ('R_ONLY', '1993');
INSERT INTO public.programming_languages (value, release_year) VALUES ('RUBY', '1995');
INSERT INTO public.programming_languages (value, release_year) VALUES ('RUST', '2010');
INSERT INTO public.programming_languages (value, release_year) VALUES ('SCALA', '2003');
INSERT INTO public.programming_languages (value, release_year) VALUES ('SHELL', '1977');
INSERT INTO public.programming_languages (value, release_year) VALUES ('SMALL_TALK', '1972');
INSERT INTO public.programming_languages (value, release_year) VALUES ('SQL', '1972');
INSERT INTO public.programming_languages (value, release_year) VALUES ('SWIFT', '2014');
INSERT INTO public.programming_languages (value, release_year) VALUES ('TYPESCRIPT', '2012');
INSERT INTO public.programming_languages (value, release_year) VALUES ('VISUAL_BASIC', '2012');
INSERT INTO public.spoken_languages (value) VALUES ('AF');
INSERT INTO public.spoken_languages (value) VALUES ('AR');
INSERT INTO public.spoken_languages (value) VALUES ('BG');
INSERT INTO public.spoken_languages (value) VALUES ('BS');
INSERT INTO public.spoken_languages (value) VALUES ('CA');
INSERT INTO public.spoken_languages (value) VALUES ('CS');
INSERT INTO public.spoken_languages (value) VALUES ('CY');
INSERT INTO public.spoken_languages (value) VALUES ('DA');
INSERT INTO public.spoken_languages (value) VALUES ('DE');
INSERT INTO public.spoken_languages (value) VALUES ('EL');
INSERT INTO public.spoken_languages (value) VALUES ('EN');
INSERT INTO public.spoken_languages (value) VALUES ('ES');
INSERT INTO public.spoken_languages (value) VALUES ('ET');
INSERT INTO public.spoken_languages (value) VALUES ('FA');
INSERT INTO public.spoken_languages (value) VALUES ('FI');
INSERT INTO public.spoken_languages (value) VALUES ('FR');
INSERT INTO public.spoken_languages (value) VALUES ('HE');
INSERT INTO public.spoken_languages (value) VALUES ('HI');
INSERT INTO public.spoken_languages (value) VALUES ('HR');
INSERT INTO public.spoken_languages (value) VALUES ('HU');
INSERT INTO public.spoken_languages (value) VALUES ('ID');
INSERT INTO public.spoken_languages (value) VALUES ('IT');
INSERT INTO public.spoken_languages (value) VALUES ('JA');
INSERT INTO public.spoken_languages (value) VALUES ('KO');
INSERT INTO public.spoken_languages (value) VALUES ('LT');
INSERT INTO public.spoken_languages (value) VALUES ('LV');
INSERT INTO public.spoken_languages (value) VALUES ('MK');
INSERT INTO public.spoken_languages (value) VALUES ('MS');
INSERT INTO public.spoken_languages (value) VALUES ('MY');
INSERT INTO public.spoken_languages (value) VALUES ('NL');
INSERT INTO public.spoken_languages (value) VALUES ('NO');
INSERT INTO public.spoken_languages (value) VALUES ('PL');
INSERT INTO public.spoken_languages (value) VALUES ('PT');
INSERT INTO public.spoken_languages (value) VALUES ('RO');
INSERT INTO public.spoken_languages (value) VALUES ('RU');
INSERT INTO public.spoken_languages (value) VALUES ('SK');
INSERT INTO public.spoken_languages (value) VALUES ('SL');
INSERT INTO public.spoken_languages (value) VALUES ('SQ');
INSERT INTO public.spoken_languages (value) VALUES ('SV');
INSERT INTO public.spoken_languages (value) VALUES ('TH');
INSERT INTO public.spoken_languages (value) VALUES ('TL');
INSERT INTO public.spoken_languages (value) VALUES ('TR');
INSERT INTO public.spoken_languages (value) VALUES ('UK');
INSERT INTO public.spoken_languages (value) VALUES ('VI');
INSERT INTO public.spoken_languages (value) VALUES ('ZH');
INSERT INTO public.work_location_types (value) VALUES ('ALWAYS_ON_SITE');
INSERT INTO public.work_location_types (value) VALUES ('ALWAYS_REMOTE');
INSERT INTO public.work_location_types (value) VALUES ('FLEXIBLE');
INSERT INTO public.work_status_types (value) VALUES ('CONTRACT');
INSERT INTO public.work_status_types (value) VALUES ('FULL_TIME');
INSERT INTO public.work_status_types (value) VALUES ('FULL_TIME_OR_CONTRACT');
INSERT INTO public.work_vacation_durations (value) VALUES ('FIVE_WEEKS');
INSERT INTO public.work_vacation_durations (value) VALUES ('FOUR_WEEKS');
INSERT INTO public.work_vacation_durations (value) VALUES ('NO_PREFERENCE');
INSERT INTO public.work_vacation_durations (value) VALUES ('ONE_WEEK');
INSERT INTO public.work_vacation_durations (value) VALUES ('THREE_WEEKS');
INSERT INTO public.work_vacation_durations (value) VALUES ('TWO_WEEKS');
INSERT INTO public.work_vacation_durations (value) VALUES ('UNLIMITED');
